// import '../system/plugins/modules/prismjs'
// import 'prismjs/prism.js'
// import 'prismjs/components/prism-bash.js'
// import 'prismjs/components/prism-javascript.js'
// import 'prismjs/components/prism-scss.js'
// import 'prismjs/components/prism-css.js'
// import 'prismjs/components/prism-json.js'
// import 'prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.js'
import 'bootstrap'
